### PR TITLE
Eliminate WD warnings during site installation

### LINKED ISSUE #7: warnings during installation
i'm getting these consistently while running the installer via drush 

``` bash
$ drush site-install ucsf_installprofile --db-url="mysql://XXX:XXXX@localhost/starterkit"
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;load() (line 173 of                                                                     [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;cacheGet() (line 350 of                                                                 [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;load() (line 173 of                                                                     [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;cacheGet() (line 350 of                                                                 [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;load() (line 173 of                                                                     [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;cacheGet() (line 350 of                                                                 [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;load() (line 173 of                                                                     [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;cacheGet() (line 350 of                                                                 [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;load() (line 173 of                                                                     [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;cacheGet() (line 350 of                                                                 [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;load() (line 173 of                                                                     [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
array_flip(): Can only flip STRING and INTEGER values! in DrupalDefaultEntityController-&gt;cacheGet() (line 350 of                                                                 [warning]
/home/stefan/dev/projects/ucsf_installprofile/webroot/includes/entity.inc).
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
mkdir(): File exists in DrupalLocalStreamWrapper-&gt;mkdir() (line 639 of /home/stefan/dev/projects/ucsf_installprofile/webroot/includes/stream_wrappers.inc).                      [warning]
mkdir(): File exists in DrupalLocalStreamWrapper-&gt;mkdir() (line 639 of /home/stefan/dev/projects/ucsf_installprofile/webroot/includes/stream_wrappers.inc).                      [warning]
mkdir(): File exists in DrupalLocalStreamWrapper-&gt;mkdir() (line 639 of /home/stefan/dev/projects/ucsf_installprofile/webroot/includes/stream_wrappers.inc).                      [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
mkdir(): File exists in DrupalLocalStreamWrapper-&gt;mkdir() (line 639 of /home/stefan/dev/projects/ucsf_installprofile/webroot/includes/stream_wrappers.inc).                      [warning]
mkdir(): File exists in DrupalLocalStreamWrapper-&gt;mkdir() (line 639 of /home/stefan/dev/projects/ucsf_installprofile/webroot/includes/stream_wrappers.inc).                      [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in taxonomy_build_node_index() (line 1958 of /home/stefan/dev/projects/ucsf_installprofile/webroot/modules/taxonomy/taxonomy.module).                           [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]
Illegal offset type in isset or empty in pathauto_cleanstring() (line 180 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).[warning]
Illegal offset type in pathauto_cleanstring() (line 223 of /home/stefan/dev/projects/ucsf_installprofile/webroot/sites/all/modules/patched/pathauto/pathauto.inc).                  [warning]

```

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #7.
with the exception of that pesky warning that WebEdit alway emits, we're in the clear.

### CODE REVIEW

**Comment by erykmynn** [comment]
what is the webedit warning?

-Eric

**Comment by stopfstedt** [comment]
@erykmynn, the warning is "WebEdit user roles might not be enabled yet. You must visit the settings page to enable use. [warning]"

**Comment by erykmynn** [comment]
I believe that is a notice, not a warning.  If it is a warning, I should
change it to a notice.

-Eric

On Wed, Jul 23, 2014 at 10:04 AM, Stefan Topfstedt <notifications@github.com

**Comment by stopfstedt** [comment]
here you go @erykmynn ucsf-drupal/ucsf_webedit#5

**Pull request merged**
