### PR TITLE
fixed dependencies for running behat tests locally

### LINKED ISSUE #166: behat tests broken
tried to run these locally via Selenium, and got fatal errors all over the place.

looks like latest firefox and latest selenium are not jiving together.

all libs got installed via composer.

i'm running FF 39 and Oracle Java 7 on Linux.

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #166.

### CODE REVIEW

**Comment by stopfstedt** [comment]
alright, this should work now. had to bump up the version number on the drupal/behat extension package as well, b/c the previously used stable release kept breaking.

**Comment by johnkealy** [comment]
Still failing a check, but we've been failing that for a while :(

**Comment by stopfstedt** [comment]
@johnkealy - to clarify:  this PR restores the ability to run the tests locally. 
things are still messed up on travis b/c the saucelabs integration is jacked.

**Comment by stopfstedt** [comment]
and yes, some of the test are broken, but that's another issue.

**Pull request merged**
